package main

import (
	"log"
	"os"

	"github.com/xesina/golang-echo-realworld-example-app/db"
	"github.com/xesina/golang-echo-realworld-example-app/handler"
	"github.com/xesina/golang-echo-realworld-example-app/router"
	"github.com/xesina/golang-echo-realworld-example-app/store"

	beeline "github.com/honeycombio/beeline-go"

	echoSwagger "github.com/swaggo/echo-swagger"                 // echo-swagger middleware
	_ "github.com/xesina/golang-echo-realworld-example-app/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

const hnyDataset = "realworld"

func main() {
	// Initialize beeline
	hnyWriteKey := os.Getenv("HONEYCOMB_WRITEKEY")
	if hnyWriteKey == "" {
		log.Println("WARN - HONEYCOMB_WRITEKEY is not set")
	}
	beeline.Init(beeline.Config{
		WriteKey:    hnyWriteKey,
		Dataset:     hnyDataset,
		ServiceName: "realworld-echo",
		// for demonstration, send the event to STDOUT intead of Honeycomb.
		// Remove the STDOUT setting when filling in a real write key.
		//STDOUT: true,
	})
	// ensure all events are flushed before we exit
	defer beeline.Close()

	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	as := store.NewArticleStore(d)
	h := handler.NewHandler(us, as)
	h.Register(v1)
	r.Logger.Fatal(r.Start("127.0.0.1:8585"))
}
